export function REQUEST(actionType) {
    return {
        type: actionType,
    };
}

export function SUCCESS(actionType, response) {
    return {
        type: actionType,
        payload: response,
    };
}

export function FAILURE(actionType, error) {
    return {
        type: actionType,
        payload: error,
    };
}

export const USER_REQUEST = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    REMOVE_USER_REQUEST: 'REMOVE_USER_REQUEST',
    REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
    REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

    CREATE_REQUEST: 'CREATE_REQUEST',
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATE_FAILURE',

    RESET_USER_DATA: 'RESET_USER_DATA',

    GET_USERS_BY_TEAM_LEAD_REQUEST: 'GET_USERS_BY_TEAM_LEAD_REQUEST',
    GET_USERS_BY_TEAM_LEAD_SUCCESS: 'GET_USERS_BY_TEAM_LEAD_SUCCESS',
    GET_USERS_BY_TEAM_LEAD_FAILURE: 'GET_USERS_BY_TEAM_LEAD_FAILURE',
};

export const ATTENDANCE_REQUEST = {
    CHECKIN_USER_REQUEST: 'CHECKIN_USER_REQUEST',
    CHECKIN_USER_SUCCESS: 'CHECKIN_USER_SUCCESS',
    CHECKIN_USER_FAILURE: 'CHECKIN_USER_FAILURE',

    GET_USER_ATTENDANCE_REQUEST: 'GET_USER_ATTENDANCE_REQUEST',
    GET_USER_ATTENDANCE_SUCCESS: 'GET_USER_ATTENDANCE_SUCCESS',
    GET_USER_ATTENDANCE_FAILURE: 'GET_USER_ATTENDANCE_FAILURE',

    DELETE_ATTENDANCE_BY_ADMIN_REQUEST: 'DELETE_ATTENDANCE_BY_ADMIN_REQUEST',
    DELETE_ATTENDANCE_BY_ADMIN_SUCCESS: 'DELETE_ATTENDANCE_BY_ADMIN_SUCCESS',
    DELETE_ATTENDANCE_BY_ADMIN_FAILURE: 'DELETE_ATTENDANCE_BY_ADMIN_FAILURE',

    EDIT_ATTENDANCE_BY_USER_REQUEST: 'EDIT_ATTENDANCE_BY_USER_REQUEST',
    EDIT_ATTENDANCE_BY_USER_SUCCESS: 'EDIT_ATTENDANCE_BY_USER_SUCCESS',
    EDIT_ATTENDANCE_BY_USER_FAILURE: 'EDIT_ATTENDANCE_BY_USER_FAILURE',

    GET_ATTENDANCE_DETAIL_BY_ID_REQUEST: 'GET_ATTENDANCE_DETAIL_BY_ID_REQUEST',
    GET_ATTENDANCE_DETAIL_BY_ID_SUCCESS: 'GET_ATTENDANCE_DETAIL_BY_ID_SUCCESS',
    GET_ATTENDANCE_DETAIL_BY_ID_FAILURE: 'GET_ATTENDANCE_DETAIL_BY_ID_FAILURE',

    RESET_ATTENDANCE_DATA: 'RESET_ATTENDANCE_DATA',
};


export const LEAVE_REQUEST = {
    CREATE_LEAVE_REQUEST: 'CREATE_LEAVE_REQUEST',
    CREATE_LEAVE_SUCCESS: 'CREATE_LEAVE_SUCCESS',
    CREATE_LEAVE_FAILURE: 'CREATE_LEAVE_FAILURE',

    GET_ALL_LEAVES_REQUEST: 'GET_ALL_LEAVES_REQUEST',
    GET_ALL_LEAVES_SUCCESS: 'GET_ALL_LEAVES_SUCCESS',
    GET_ALL_LEAVES_FAILURE: 'GET_ALL_LEAVES_FAILURE',

    EDIT_LEAVE_REQUEST: 'EDIT_LEAVE_REQUEST',
    EDIT_LEAVE_SUCCESS: 'EDIT_LEAVE_SUCCESS',
    EDIT_LEAVE_FAILURE: 'EDIT_LEAVE_FAILURE',

    GET_LEAVE_BY_ID_REQUEST: 'GET_LEAVE_BY_ID_REQUEST',
    GET_LEAVE_BY_ID_SUCCESS: 'GET_LEAVE_BY_ID_SUCCESS',
    GET_LEAVE_BY_ID_FAILURE: 'GET_LEAVE_BY_ID_FAILURE',

    DELETE_LEAVE_REQUEST: 'DELETE_LEAVE_REQUEST',
    DELETE_LEAVE_SUCCESS: 'DELETE_LEAVE_SUCCESS',
    DELETE_LEAVE_FAILURE: 'DELETE_LEAVE_FAILURE',

    GET_USER_LEAVES_REQUEST: 'GET_USER_LEAVES_REQUEST',
    GET_USER_LEAVES_SUCCESS: 'GET_USER_LEAVES_SUCCESS',
    GET_USER_LEAVES_FAILURE: 'GET_USER_LEAVES_FAILURE',


    UPDATE_LEAVE_STATUS_REQUEST: 'UPDATE_LEAVE_STATUS_REQUEST',
    UPDATE_LEAVE_STATUS_SUCCESS: 'UPDATE_LEAVE_STATUS_SUCCESS',
    UPDATE_LEAVE_STATUS_FAILURE: 'UPDATE_LEAVE_STATUS_FAILURE',
};






